Add additional typings
CCDirectLink/ultimate-crosscode-typedefs pull request #2
Opened 2023-08-03 01:55 UTC by EL20202

As you can tell, contains a _lot_ of types from all over.

2023-08-11 18:17 UTC, lexisother requested changes
Sorry for the pedanticism!

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.arena.arena.d.ts
> +      onEnemyBreak(this: this, enemy: ig.ENTITY.Enemy): void;
```suggestion
      onEnemyBreak(this: this, enemy: ig.ENTITY.Enemy): void;
      hasChallenge(this: this, challenge: keyof sc.ARENA_CHALLENGES): boolean;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.arena.arena.d.ts
> +
Duplicate?

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.combat.combat.d.ts
> +      onCombatantDeathHit(this: this, attacker: ig.ENTITY.Combatant, victim: ig.ENTITY.Combatant): void;
Ordering
```suggestion
      onCombatantDeathHit(this: this, attacker: ig.ENTITY.Combatant, victim: ig.ENTITY.Combatant): void;
      showModeChange(this: this, combatant: ig.ENTITY.Combatant, element: sc.ELEMENT): ig.ENTITY.Effect;
      showModeAura(this: this, combatant: ig.ENTITY.Combatant, element: sc.ELEMENT): void;
      clearModeAura(this: this, combatant: ig.ENTITY.Combatant): void;
      showModeDash(this: this, combatant: ig.ENTITY.Combatant, element: sc.ELEMENT): void;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.combat.entities.ball.d.ts
> +      isBall?: boolean;
Ordering
```suggestion
      isBall?: boolean;
      attackInfo: sc.AttackInfo;
      remainingHits: number;
      timer: number;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.combat.entities.projectile.d.ts
> +      getElement(this: this): sc.ELEMENT;
Ordering
```suggestion
      getElement(this: this): sc.ELEMENT;
      getCombatantRoot(this: this): ig.ENTITY.Combatant;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.combat.model.combat-params.d.ts
> +      buffs: sc.StatChange[];
Remove wrong position
```suggestion
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.combat.model.combat-params.d.ts
>        currentHp: number;
```suggestion
      modifiers: Record<keyof sc.MODIFIERS, number>;
      buffs: sc.StatChange[];
      currentHp: number;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.combat.model.combat-params.d.ts
> +      setMaxSp(this: this, maxSp: number): void;
Fixed ordering of all of these because even the existing ones were wrong
```suggestion
      setCombatant(this: this, combatant: ig.ENTITY.Combatant): void;
      setModifiers(this: this, modifiers: sc.ModifierList): void;
      reset(this: this, maxSp: number): void;
      setMaxSp(this: this, maxSp: number): void;
      setBaseParams(this: this, baseParams: sc.CombatParams.BaseParams): void;
      getDamage(this: this, attackInfo: sc.AttackInfo, damageFactorMod: number, combatant: ig.ENTITY.Combatant, shieldResult?: sc.SHIELD_RESULT, hitIgnore?: boolean): CombatParams.DamageResult;
      getHealAmount(this: this, healInfo: sc.HealInfoType): number;
      setCritical(this: this): void;
      increaseHp(this: this, amount: number): void;
      getHpFactor(this: this): number;
      addSp(this: this, spAdd: number, maxSp?: number): void;
      setRelativeSp(this: this, factor: number): void;
      consumeSp(this: this, sp: number): void;
      setRelativeHp(this: this, ratio: number): void;
      getSp(this: this): number;
      getRelativeSp(this: this): number;
      notifySpConsume(this: this, sp: number): void;      
      isDefeated(this: this): boolean;
      addBuff(this: this, buff: sc.StatChange): true;
      removeBuff(this: this, buff: sc.StatChange): void;
      removeAllBuffs(this: this): void;
      update(this: this, inCombat: boolean): void;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.combat.model.combat-params.d.ts
>        critFactor: number;
Ordering
```suggestion
      element: sc.ELEMENT;
      critFactor: number;
      spFactor: number;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.combat.model.enemy-type.d.ts
> +      enduranceScale: number;
Misplaced
```suggestion
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.combat.model.enemy-type.d.ts
>      interface EnemyType extends ig.JsonLoadable {
Fix placement
```suggestion
    interface EnemyType extends ig.JsonLoadable {
      enduranceScale: number;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.combat.stat-change.d.ts
> +      onEntityKillDetach(this: this): void;
These don't exist on the base `sc.StatChange` class? Or did you add this because everything that extends it does?

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.combat.stat-change.d.ts
> +      reset(this: this, time: number): void;
Doesn't exist on `sc.StatChange`

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.control.control.d.ts
> +      menuBack(this: this): boolean;
Additionally, `moveDir` must be below `autoThrown`, but I couldn't include it in the suggestion because the line containing the function name is outside of the hunk in this diff
```suggestion
      getMouseX(this: this): number;
      getMouseY(this: this): number;
      autoThrown(this: this): boolean;
      menuBack(this: this): boolean;
      menuHotkeyHelp(this: this): boolean;
      menuHotkeyHelp2(this: this): boolean;
      menuHotkeyHelp3(this: this): boolean;
      menuScrollUp(this: this): boolean;
      menuScrollDown(this: this): boolean;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.gui.base.button.d.ts
> +      submitSound?: ig.Sound;
Fix ordering
```suggestion
      text: sc.TextLike;
      bgGui: sc.ButtonBgGui;
      buttonType: sc.ButtonGui.Type;
      submitSound?: ig.Sound;
      data?: unknown;
      textChild: sc.TextGui;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.gui.widget.modal-dialog.d.ts
> +
Unnecessary spacing
```suggestion
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.interact.button-group.d.ts
>      }
Frankly this entire class confuses me as none of these properties or methods are actually on `sc.ButtonGroup`, they are on `ig.ButtonGroup`. Perhaps move them over?

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.inventory.inventory.d.ts
> +      isBuffID(this: this, id: sc.ItemID): boolean
Fixed ordering
```suggestion
      updateScaledEquipment(this: this, newLevel: number): void;
      getItem(id: sc.ItemID): Optional<sc.Inventory.Item>;
      getItemName(this: this, id: sc.ItemID): string;
      getBuffString(this: this, id: sc.ItemID, a?: boolean, statChangeSettings?: string[]): string | undefined;
      isBuffID(this: this, id: sc.ItemID): boolean
      getRaritySuffix(this: this, rarity: sc.ITEMS_RARITY): string;
      getItemNameWithIcon(this: this, id: sc.ItemID): string;
      getItemIcon(this: this, id: sc.ItemID): string;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.menu.gui.equip.equip-bodypart.d.ts
> +      showMenu(this: this): void;
Fix ordering
```suggestion
      showMenu(this: this): void;
      _moveButtons(this: this, bodypart: sc.MENU_EQUIP_BODYPART): void;
      _pullInAllButtons(this: this, exception: ig.FocusGui): void;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.gui.widget.timer-gui.d.ts
> +
Unnecessary spacing
```suggestion
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.menu.gui.equip.equip-bodypart.d.ts
> +
Unnecessary spacing
```suggestion
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.menu.gui.item.item-sort-menu.d.ts
> +            showSortMenuAt(this: this, x: number, y: number): void;
Fix ordering
```suggestion
            buttongroup: sc.ButtonGroup;
            active: boolean;

            // enumIndex is normally referring to an sc.SORT_TYPE, but it does not have to be (i.e. sc.QUEST_SORT_TYPE)
            addButton(key: string, enumIndex: number, buttonIndex: number): void;
            showSortMenu(this: this, referenceGUI: ig.GuiElementBase): void;
            showSortMenuAt(this: this, x: number, y: number): void;
            hideSortMenu(this: this): void;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.menu.gui.item.item-status-default.d.ts
> +      barHeight: number;
Fix ordering
```suggestion
      type: sc.MENU_BAR_TYPE;
      maxValue: number;
      currentValue: number;
      targetValue: number;
      currentNumber: sc.NumberGui;
      maxNumber: sc.NumberGui;
      barHeight: number;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.menu.gui.list-boxes.d.ts
> +      getScrollY(this: this): number;
Doesn't exist on `sc.ButtonListBox`, but on `sc.ScrollPane`

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.menu.gui.list-boxes.d.ts
> +      clear(this: this, refocus: boolean): void;
Fix ordering
```suggestion
      clear(this: this, refocus: boolean): void;
      buttonGroup(this: this): sc.ButtonGroup;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.menu.gui.options.options-misc.d.ts
> +      setSize(this: this, x: number, y: number, sliderHeight: number): void;
Fix ordering
```suggestion
      setPreferredThumbSize(this: this, width: number, height: number): void;
      setSize(this: this, x: number, y: number): void;
      setSize(this: this, x: number, y: number, sliderHeight: number): void;
      setValue(this: this, value: number): void;
      setMinMaxValue(this: this, min: number, max: number): void;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.menu.gui.social.social-misc.d.ts
> +
Unnecessary spacing
```suggestion
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.menu.menu-model.d.ts
> +      previousMenu: sc.MENU_SUBMENU;
Additionally, `backCallbackStack` should be under `buttonInteract` but I could not add it to the suggestion because the hunk is outside this diff
```suggestion
      previousMenu: sc.MENU_SUBMENU;
      buttonInteract: ig.ButtonInteractEntry;
      hotkeysCallbacks: sc.MenuModel.HotkeyCallback;
      currentBackCallback: sc.MenuModel.BackCallback;
      shopID: Optional<string>;
      shopPage: number;
      shopCart: sc.MenuModel.ShopCartEntry[];
      shopSellMode: boolean;
      statusElement: sc.ELEMENT;
      statusDiff: boolean;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.model.game-model.d.ts
> +      isQuickMenu(this: this): boolean;
Fix ordering
```suggestion
      addChoiceGui(this: this, choiceGui: ig.GuiElementBase): void;
      removeChoiceGui(this: this, choiceGui: ig.GuiElementBase): void;
      getCombatRankDropRate(this: this): number;
      isAssistMode(this: this): boolean;
      setMobilityBlock(this: this, mobilityBlock: keyof sc.GAME_MOBILITY_BLOCK): void;
      enterCutscene(this: this, combatCutscene?: boolean): void;
      enterGame(this: this): void;
      enterPrevSubState(this: this): void;
      enterMenu(this: this, force?: Optional<boolean>): void;
      isCutscene(this: this): boolean;
      isQuickMenu(this: this): boolean;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.model.options-model.d.ts
> +      hdMode: boolean;
Fix ordering
```suggestion
      hdMode: boolean;
      hasChanged: boolean;
      values: ig.Storage.GlobalsData.Options;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.new-game.new-game-model.d.ts
> +      applyStoreData(this: this, atRhombus: boolean): void;
Fix ordering
```suggestion
      applyStoreData(this: this, atRhombus: boolean): void;
      getDropRateMultiplier(this: this): number;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.party.party-member-model.d.ts
> +      currentElementMode: sc.ELEMENT;
Fix ordering
```suggestion
      config: sc.PlayerConfig;
      params: sc.CombatParams;
      elementConfigs: Record<sc.ELEMENT, sc.PlayerSubConfig>;
      healing: PartyMemberModel.Healing;
      currentElementMode: sc.ELEMENT;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.party.party-member-model.d.ts
> +      updateStats(this: this): void;
Fix ordering
```suggestion
      getHeadIdx(this: this): number;
      updateStats(this: this): void;
      revive(this: this): void;
      setTemporary(this: this, a: boolean): void;
      setNoDie(this: this, a: boolean): void;
      update(this: this): void;
      reset(this: this): void;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.player.entities.player.d.ts
> +      gui: Player.Gui;
Fix ordering
```suggestion
      model: sc.PlayerModel;
      attackCounter: number;
      dashCount: number;
      dashAttackCount: number;
      maxDash: number;
      jumpPoint: Vec2;
      jumpForwardDir: Vec2;
      gui: Player.Gui;
      dashTimer: number;
      dashBlock: number;
      charging: ig.ENTITY.Player.Charging;
      isPlayer: true;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.player.entities.player.d.ts
> +      onHeal(this: this, healInfo: sc.HealInfo.Settings | sc.HealInfo, amount: number): void
Fix ordering
```suggestion
      updateSkinAura(this: this): void;
      updateModelStats(this: this, a: boolean): void;
      showChargeEffect(this: this, level: number): void;
      getMaxChargeLevel(this: this, actionKey: Player.ActionKey): 0 | 1 | 2 | 3;
      getChargeAction(this: this, chargeType: ig.ENTITY.Player.Charging.Type, level: number): string;
      gatherInput(this: this): ig.ENTITY.Player.PlayerInput;
      handleStateStart(
        this: this,
        playerState: ig.ENTITY.Player.PlayerState,
        inputState: ig.ENTITY.Player.PlayerInput,
      ): void;
      onPerfectDash(this: this): void;
      onHeal(this: this, healInfo: sc.HealInfo.Settings | sc.HealInfo, amount: number): void
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.player.player-config.d.ts
> +      autoequip: PlayerConfig.AutoEquip;
Fix ordering
```suggestion
      name: string;
      stats: PlayerConfig.Stats;
      autoequip: PlayerConfig.AutoEquip;
      baseConfig: sc.PlayerSubConfig;
      elementConfigs: Record<sc.ELEMENT, sc.PlayerSubConfig>;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.player.player-config.d.ts
> +      skillFactors: PlayerSubConfig.Factor;
Fix ordering
```suggestion
      paramFactors?: PlayerSubConfig.Factor;
      skillFactors: PlayerSubConfig.Factor;
      actions: Record<string, sc.PlayerAction>;
      baseParams: sc.CombatParams.BaseParams;
      modifiers: sc.ModifierList;
      activeActions: Record<number, sc.PlayerAction>;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.player.player-config.d.ts
> +      preSkillInit(this: this): void;
Fix ordering
```suggestion
      preSkillInit(this: this): void;
      update(this: this, config: sc.CombatParams.BaseParams, modifiers: sc.ModifierList): void;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.quick-menu.gui.quick-item-menu.d.ts
> +            list: sc.ButtonListBox;
Fix ordering
```suggestion
            list: sc.ButtonListBox;
            buttongroup: sc.ButtonGroup;
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.skills.skilltree.d.ts
> +
Unnecessary spacing
```suggestion
```

2023-08-11 18:17 UTC, lexisother commented on modules/game.feature.menu.menu-model.d.ts
> +      removeHotkeys(this: this): void;
Fix ordering
```suggestion
      addHotkey(this: this, callback: sc.MenuModel.HotkeyCallback, commit?: Optional<boolean>): void;
      commitHotkeys(this: this, a?: boolean): void;
      updateHotkeys(this: this): void;
      removeHotkeys(this: this): void;
      pushBackCallback(this: this, callback: sc.MenuModel.BackCallback): void;
      popBackCallback(this: this): void;
      pushMenu(this: this, menu: sc.MENU_SUBMENU): void;
      popMenu(this: this): void;
      setDirectMode(direct?: Optional<boolean>, menu?: Optional<sc.MENU_SUBMENU>): void;
      exitMenu(this: this): void;
      moveLeaSprite(this: this, x: number, y: number, state: sc.MENU_LEA_STATE, skip?: boolean): void;
      setInfoText(this: this, text: sc.TextLike, fade?: boolean): void;
      setBuffText(this: this, text: sc.TextLike, fade?: boolean, id?: sc.ItemID): void;
      setShopPage(this: this, page: number): void;
      updateCart(this: this, itemID: sc.ItemID, amount: number, price: number): void;
      getTotalCost(this: this): number;
      getItemQuantity(this: this, itemID: sc.ItemID, price: number): number;
      sortList(this: this, button: ig.FocusGui): void;
```

2023-08-11 19:42 UTC, remty5 requested changes
Here's the remaining files from lexi's review.

2023-08-11 19:42 UTC, rosalinadev commented on modules/impact.feature.interact.gui.focus-gui.d.ts
> +
Duplicate? Also missing methods.

```suggestion
      canLeaveFocus(this: this): boolean;
      setPressed(this: this, pressed: boolean): void;
      setActive(this: this, active: boolean): void;
      isSameAs(this: this, other: ig.FocusGui): boolean;
```

2023-08-11 19:42 UTC, rosalinadev commented on modules/impact.feature.gamepad.gamepad.d.ts
> +
Missing method?
```suggestion
            isRightStickDown(this: this): boolean;

```

2023-08-11 19:42 UTC, rosalinadev commented on modules/impact.feature.effect.entities.effect.d.ts
>        spawnParticle<E extends ig.Entity, S extends ig.Entity.Settings>(
Misordered methods
```suggestion
      isDone(this: this): boolean;
      spawnParticle<E extends ig.Entity, S extends ig.Entity.Settings>(
```

2023-08-11 19:42 UTC, rosalinadev commented on modules/impact.feature.effect.entities.effect.d.ts
> +      isDone(this: this): boolean;
Remove misordered method
```suggestion
```

2023-08-11 19:42 UTC, rosalinadev commented on modules/impact.base.sprite.d.ts
> +
Misordered methods
```suggestion

      setPos(this: this, x: number, y: number, z: number): void;
      setGfxCut(this: this, top: number, bottom: number, left: number, right: number): void;
      setShadow(
        this: this,
        x: number,
        y: number,
        z: number,
        diameter: number,
        type?: ig.COLL_SHADOW_TYPE,
        scaleY?: number
      ): void;
```

2023-08-11 19:42 UTC, rosalinadev commented on modules/impact.base.sprite.d.ts
> +      setGfxCut(this: this, top: number, bottom: number, left: number, right: number): void;
Misordered methods
```suggestion
      setOverlayColor(this: this, color: string, alpha: number): void;
      setLighterOverlayColor(this: this, color: string, alpha: number): void;
      setInvisible(this: this): void;
      setEntityDefault(
        this: this,
        entity: ig.Entity,
        tileWidth: number,
        tileHeight: number,
        shapeType: keyof typeof ig.ANIM_SHAPE_TYPE,
        wallY: number,
        offset: Vec3 | null,
        image: ig.Image,
        srcX: number,
        srcY: number,
      ): void;
```

2023-08-11 19:42 UTC, rosalinadev commented on modules/impact.base.input.d.ts
> +      keydown(this: this, action: LiteralUnion<ig.Input.KnownAction>): boolean;
Misordered, please move before `bind()`.

2023-08-11 19:42 UTC, rosalinadev commented on modules/impact.base.image.d.ts
Misordered method
```suggestion

      addCallback(this: this, callback: Image.Callback): void;
```

2023-08-11 19:42 UTC, rosalinadev commented on modules/impact.base.image.d.ts
> +      resize(this: this, scale: number): void;
Order should be `resize()`, `draw()` and then `createPattern()`, please move accordingly.
```suggestion
```

2023-08-11 19:42 UTC, rosalinadev commented on modules/impact.base.image.d.ts
> +      addCallback(this: this, callback: Image.Callback): void;
Remove misordered method.
```suggestion
```

2023-08-11 19:42 UTC, rosalinadev commented on modules/impact.base.game.d.ts
> +      events: ig.EventManager;
Misordered properties
```suggestion
      paused: boolean;
      mapName: string;
      entities: ig.Entity[];
      events: ig.EventManager;
      physics: ig.Physics;
      playerEntity: ig.ENTITY.Player;
      addons: Game.Addons;
```

2023-08-11 19:42 UTC, rosalinadev commented on modules/impact.base.game.d.ts
> +      ): ig.Entity[];
Misordered methods
```suggestion
      getEntitiesInCircle(
        center: Vec3,
        radius: number,
        yScale: number,
        zHeight: number,
        dir: Vec2,
        startAngle: number,
        endAngle: number,
        exception?: ig.Entity,
        moreExceptions?: ig.Entity[],
        rectangular?: boolean
      ): ig.Entity[];
      getEntitiesByType<E extends ig.Entity, S extends ig.Entity.Settings>(
        this: this,
        type: new (x: number, y: number, z: number, settings: S) => ig.Entity,
      ): E[];
```

2023-08-11 19:42 UTC, rosalinadev commented on modules/impact.base.entity.d.ts
> +      initAnimations(this: this, sheet: ig.AnimationSheet | string | unknown): void;
Misordered methods
```suggestion
      initAnimations(this: this, sheet: ig.AnimationSheet | string | unknown): void;
      setCurrentAnim(this: this, name: string, reset?: boolean, followUp?: Optional<string>, force?: boolean, callbackOnFinish?: boolean): void;
```

2023-08-11 19:42 UTC, rosalinadev commented on modules/game.main.d.ts
> +      addTeleportMessage(this: this, message: string): void;
Misordered methods
```suggestion
      addTeleportMessage(this: this, message: string): void;
      start(this: this, startMode?: sc.START_MODE, transitionTime?: number): void;
```

2023-08-11 19:42 UTC, remty5 commented on modules/impact.base.coll-entry.d.ts
> +      shadow: CollEntry.Shadow;
Misordered properties, and while it's not from your changes, `relativeVel` is wrongly typed.
```suggestion
      type: COLLTYPE;
      size: Vec3;
      weight: number;
      relativeVel: number;
      zBounciness: number;
      zGravityFactor: number;
      pos: Vec3;
      level: number;
      baseZPos: number;
      shadow: CollEntry.Shadow;
      vel: Vec3;
```

2023-08-11 19:42 UTC, remty5 commented on modules/impact.base.entity.d.ts
> +      ballDestroyer?: boolean;
Misordered properties, also `isPlayer` could get the same treatment as `ballDestroyer`.
```suggestion
      sprites: ig.CubeSprite[];
      entityAttached: ig.Entity.Attachable[];
      _killed: boolean;
      
      ballDestroyer?: boolean;
      isPlayer?: boolean;
```

2023-08-12 18:28 UTC, lexisother commented on modules/game.feature.puzzle.entities.compressor.d.ts
> +            attackInfo: sc.AttackInfo;
Fix ordering
```suggestion
            nudgeTimer: number;
            killTimer: number;
            globalCount: number;
            speedFactor: number;
            combatant: ig.ENTITY.Combatant;
            attackInfo: sc.AttackInfo;
            fastMode: boolean;
```

2023-08-20 15:59 UTC, EL20202 commented on modules/game.feature.combat.stat-change.d.ts
> +      onEntityKillDetach(this: this): void;
Yes, the reason was that everything that extends it does, and what uses a `sc.StatChange` expects those functions - even if the base class itself does not have them. I will add a note specifying that. I will say that `onActionEndDetach` and `onEntityKillDetach` however are misplaced and as such are moved to `ActionBuff`.

2023-08-20 16:50 UTC, EL20202 commented
There, that should be everything.

2023-08-20 21:56 UTC, lexisother commented
I'll review the new content tomorrow. Thank you!

2023-08-21 19:09 UTC, lexisother approved these changes
LGTM, thank you for the big contribution!

2023-08-21 20:40 UTC, EL20202 commented
There, I fixed the one issue I noticed earlier today. Feel free to merge now!

2023-08-23 21:13 UTC, merged